steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - --tag
      - asia-southeast1-docker.pkg.dev/the49-487609/ddbox/content-api:${_IMAGE_TAG}
      - services/content-api
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-southeast1-docker.pkg.dev/the49-487609/ddbox/content-api:${_IMAGE_TAG}
images:
  - asia-southeast1-docker.pkg.dev/the49-487609/ddbox/content-api:${_IMAGE_TAG}
serviceAccount: projects/the49-487609/serviceAccounts/ddbox-deployer@the49-487609.iam.gserviceaccount.com
logsBucket: gs://the49-487609-ddbox-build/logs/content-api-image
options:
  logging: GCS_ONLY
  machineType: E2_HIGHCPU_8
substitutions:
  _IMAGE_TAG: required
